edit_uri: edit/master/docs/
site_author: Joerg Hochwald
copyright: ExchangeNodeMaintenanceMode is licensed under the <a href='https://github.com/jhochwald/PowerShell-collection/master/LICENSE.md'> license
theme: readthedocs
site_name: ExchangeNodeMaintenanceMode Docs
Pages:
  ChangeLog: ChangeLog.md
  Functions:
  - Invoke-ApplyExchangeCumulativeUpdate: Functions\Invoke-ApplyExchangeCumulativeUpdate.md
  - Invoke-Exchange2016Workaround: Functions\Invoke-Exchange2016Workaround.md
  - Set-ExchangeNodeMaintenanceModeOff: Functions\Set-ExchangeNodeMaintenanceModeOff.md
  - Set-ExchangeNodeMaintenanceModeOn: Functions\Set-ExchangeNodeMaintenanceModeOn.md
  - Test-ExchangeNodeMaintenanceMode: Functions\Test-ExchangeNodeMaintenanceMode.md
  Acknowledgements: Acknowledgements.md
  Contributing: Contributing.md
  ReleaseNotes: ReleaseNotes.md
  Index: Index.md
repo_url: https://github.com/jhochwald/PowerShell-collection

